apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-deployment
  labels:
    foo: bar
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.2
        ports:
        - containerPort: 8
